### ISSUE TITLE
request help: The configuration of the config.yaml file is a bit confusing.

### ISSUE THREAD

**Issue by agile6v** [apache/incubator-apisix#1106]
Hi,

I want to add proxy_protocol flag in this file for http block and stream block seperately. But I'm not sure where to put it.

Flags look like below:
enable_http_proxy_protocol (for receive from client)
enable_tcp_proxy_protocol (for receive from client)
enable_tcp_proxy_protocol_to_upstream (for sending proxy_protocol to upstream)

Do you have any good suggestions?

Thanks.

@membphis @moonming

**Comment by agile6v** [comment]
According to the current classification,  `real_ip_header` and `real_ip_from` should be placed in `nginx_config.http`.

I would prefer to use the following way.
```yaml
nginx_config:                     # config for render the template to genarate nginx.conf
  error_log: "logs/error.log"
  error_log_level: "warn"         # warn,error
  event:
    worker_connections: 10620
  http:
     real_ip_header: "X-Real-IP" 
     real_ip_from:              
        - 127.0.0.1
        - 'unix:'
    access_log: "logs/access.log"
    keepalive_timeout: 60s         # timeout during which a keep-alive client connection will stay open on the server side.
    client_header_timeout: 60s     # timeout for reading client request header, then 408 (Request Time-out) error is returned to the client
    client_body_timeout: 60s       # timeout for reading client request body, then 408 (Request Time-out) error is returned to the client
    send_timeout: 10s              # timeout for transmitting a response to the client.then the connection is closed
  stream:
    proxy_protocol:                          true
    proxy_protocol_to_upstream:  true
    tcp:                        
      - 9100
      - 9101
    udp:                        
      - 9200
      - 9211
```
