### ISSUE TITLE
[discuss] feature: support etcd cluster in Apache APISIX.

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1231]
The etcd cluster is highly available, so Apache APISIX should allow multiple etcd addresses to be configured to connect to the etcd cluster.

How about this new style?

```yaml
etcd:
  host: 
      - "http://127.0.0.1:2379"   # multiple etcd address
      - "http://127.0.0.1:2380"  
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 3                      # 3 seconds
```

BTW, the driver `resty-etcd` has supported this feature.

https://github.com/iresty/lua-resty-etcd/blob/master/t/v2/cluster.t#L52
