### ISSUE TITLE
request help: How do I enable the plug-in when using the standalone model(local yaml)?

### ISSUE THREAD

**Issue by xxm404** [apache/incubator-apisix#1280]
### Issue description
如何在不使用 `etcd` 的模式下，开启插件

### Environment

* apisix version 1.1
* OS: Ubuntu

**Comment by membphis** [comment]
you can take a look at the test cases: https://github.com/apache/incubator-apisix/tree/master/t/config-center-yaml

**Comment by xxm404** [comment]
> you can take a look at the test cases: https://github.com/apache/incubator-apisix/tree/master/t/config-center-yaml

Modify nginx config directly?
Can i enable the limit-req plugin by modify apisix.yaml?

**Comment by membphis** [comment]
> Can i enable the limit-req plugin by modify apisix.yaml?

Of course you can do it in this way, it is the right way.

**Comment by xxm404** [comment]
> Of course, you can do it in this way, it is the right way.

i can not find plug-in config demo at apisix doc, somebody can give me a example for enable plug-in by modify apisix.yaml?

**Comment by membphis** [comment]
1. enable standalone model

```
diff --git a/conf/config.yaml b/conf/config.yaml
index d9ee014..33c9d22 100644
--- a/conf/config.yaml
+++ b/conf/config.yaml
@@ -23,7 +23,7 @@ apisix:
   enable_dev_mode: true          # Sets nginx worker_processes to 1 if set to true
   enable_reuseport: false          # Enable nginx SO_REUSEPORT switch if set to true.
   enable_ipv6: true
-  config_center: etcd             # etcd: use etcd to store the config value
+  config_center: yaml             # etcd: use etcd to store the config value
                                   # yaml: fetch the config value from local yaml file `/your_path/conf/apisix.yaml`

   #proxy_protocol:                 # Proxy Protocol configuration
```

2. start apisix

3. update conf/apisix.yaml , here is an example

https://github.com/apache/incubator-apisix/blob/master/t/config-center-yaml/route.t#L45

**Comment by xxm404** [comment]
This is my apisix.yaml，limit-req not running.
```
 routes:
   -
     uri: /hello
     service_id: 1
 services:
   -
     id: 1
     upstream:
         nodes:
             "127.0.0.1:8081": 1
         type: roundrobin
     plugins:
       limit-req:
         rate: 1
         burst: 2
         rejected_code: 503
 #END
```
