### ISSUE TITLE
feature: add a new option, decide if we remove the "/" at the end of the URI before route mathing

### ISSUE THREAD

**Issue by membphis** [apache/incubator-apisix#1765]
here is the discuss mail: https://lists.apache.org/thread.html/rd89e4e0a2d59e183afa00c8c1badf213ef45c0992f841046e129a965%40%3Cdev.apisix.apache.org%3E

add new option `delete_uri_tail_slash` in `conf/config.yaml`.

```yaml
  delete_uri_tail_slash: true     # delete the '/' at the end of the URI
  router:
    http: 'radixtree_uri'         # radixtree_uri: match route by uri(base on radixtree)
                                  # radixtree_host_uri: match route by host + uri(base on radixtree)
    ssl: 'radixtree_sni'          # radixtree_sni: match route by SNI(base on radixtree)
```
